apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-login-svc
  name: api-loadbalancer-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-login-pod
  type: LoadBalancer
